name: room_agenda
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_clean_calendar:
    git:
      url: https://github.com/walex36/flutter_clean_calendar
      ref: e8f2171

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  flutter_modular: ^5.0.3
  cloud_firestore: ^4.7.1
  firebase_core: ^2.13.0
  intl: ^0.18.0
  result_dart: ^1.0.6
  equatable: ^2.0.5
  firebase_auth: ^4.7.2
  google_sign_in: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
